import type { Metadata } from "next";
import { ClerkProvider, SignedIn, SignIn, SignedOut } from "@clerk/nextjs";
import "./globals.css";
import { Outfit } from "next/font/google";
import NavBar from "@/components/NavBar";

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Car-Rental-Service",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedIn>
            <NavBar />
            {children}
          </SignedIn>
          <SignedOut>
            <div className="flex flex-col items-center mt-20">
              <h1 className="text-5xl font-bold mb-5">Welcome to <span className="text-blue-500">Car Rental Service</span></h1>
              <SignIn routing="hash" /> 
              <p className="mt-8 font-semibold">For Demo - Email: test@gmail.com | Password: 1234</p>
            </div>
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
